import React, { useState } from 'react';
import { Button } from './Button';

export const Contact: React.FC = () => {
  const [formData, setFormData] = useState({
    identity: '',
    signal: '',
    chaos: ''
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    const message = `*NEW_TRANSMISSION*\n\n*Identity:* ${formData.identity}\n*Signal:* ${formData.signal}\n*Chaos_Description:* ${formData.chaos}\n\n_Generated by Sintax.AI_`;
    const encodedMessage = encodeURIComponent(message);
    const whatsappUrl = `https://wa.me/573115259295?text=${encodedMessage}`;

    window.open(whatsappUrl, '_blank');
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  return (
    <section id="contact" className="bg-black text-white border-b border-white/10">
      <div className="grid grid-cols-1 lg:grid-cols-2">

        <div className="p-8 md:p-24 border-b lg:border-b-0 lg:border-r border-white/10 flex flex-col justify-center">
          <h2 className="text-4xl md:text-7xl font-pixel-triangle font-bold tracking-tighter mb-4 md:mb-6">
            INITIATE<br />SEQUENCE
          </h2>
          <p className="font-mono text-xs md:text-sm text-neutral-400 max-w-md">
            Ready to purge the inefficiencies? Fill out the parameters. The system is waiting.
          </p>
        </div>

        <div className="p-8 md:p-24 bg-neutral-900/10">
          <form onSubmit={handleSubmit} className="space-y-6 md:space-y-8 max-w-lg mx-auto lg:mx-0">
            <div className="relative border-b border-white/20 focus-within:border-white transition-colors">
              <label className="font-mono text-[9px] uppercase text-neutral-500 absolute -top-3 left-0">Identity</label>
              <input
                type="text"
                name="identity"
                value={formData.identity}
                onChange={handleChange}
                required
                className="w-full bg-transparent py-3 outline-none font-mono text-base md:text-lg placeholder-white/10"
                placeholder="NAME / ORG"
              />
            </div>

            <div className="relative border-b border-white/20 focus-within:border-white transition-colors">
              <label className="font-mono text-[9px] uppercase text-neutral-500 absolute -top-3 left-0">Signal</label>
              <input
                type="email"
                name="signal"
                value={formData.signal}
                onChange={handleChange}
                required
                className="w-full bg-transparent py-3 outline-none font-mono text-base md:text-lg placeholder-white/10"
                placeholder="EMAIL ADDRESS"
              />
            </div>

            <div className="relative border-b border-white/20 focus-within:border-white transition-colors">
              <label className="font-mono text-[9px] uppercase text-neutral-500 absolute -top-3 left-0">Data Packet</label>
              <textarea
                rows={2}
                name="chaos"
                value={formData.chaos}
                onChange={handleChange}
                required
                className="w-full bg-transparent py-3 outline-none font-mono text-base md:text-lg placeholder-white/10 resize-none"
                placeholder="DESCRIBE YOUR CHAOS"
              ></textarea>
            </div>

            <div className="pt-4 md:pt-8 text-center md:text-left">
              <Button variant="outline" className="w-full justify-between" type="submit">
                <span>EXECUTE_TRANSMISSION</span>
                <span>[ENTER]</span>
              </Button>
            </div>
          </form>
        </div>

      </div>
    </section>
  );
};